# Generated by Django 2.1 on 2018-08-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumgoal',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
