# Generated by Django 2.1 on 2018-08-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0002_scrumgoal_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumgoal',
            options={'verbose_name_plural': 'Scrum Goals'},
        ),
        migrations.AlterModelOptions(
            name='scrumuser',
            options={'verbose_name_plural': 'Scrum Users'},
        ),
    ]
