# Generated by Django 2.1 on 2018-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0003_auto_20180812_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumgoal',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
