# Generated by Django 2.1 on 2018-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrum', '0004_auto_20180812_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumgoal',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Scrum Goals'},
        ),
        migrations.AlterModelOptions(
            name='scrumuser',
            options={'ordering': ['nickname'], 'verbose_name_plural': 'Scrum Users'},
        ),
        migrations.AddField(
            model_name='scrumgoal',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='scrumgoal',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
